config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/search', to: 'searches#search'

  root 'articles#home'

  resources :users do
    post :user_confirm, on: :new
    resources :relationships, only: [:create]
    resource :relationships, only: [:destroy]
    get 'followings', to: 'relationships#followings', as: 'followings'
    get 'followers', to: 'relationships#followers', as: 'followers'
  end

  resources :likes, only: [:destroy]
  resources :articles do
    resources :likes, only: [:create]
    post :article_confirm, on: :new
    member do
      post :article_confirm_edit, action: :article_confirm_edit
    end

    collection do
      get 'home'
      get 'ruby'
      get 'rails'
      get 'coldfusion'
      get 'sql'
      get 'others'
    end
  end

  resources :tags, param: :name
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true
  validates :tag_name, presence: true, length: { maximum: 50 }
  validates :category_id, presence: true
  validates :user_id, presence: true

  belongs_to :user
  belongs_to :category
  has_many :likes, dependent: :destroy

  def save_tags(articles_tag)
    articles_tag.each do |article_tag|
      # 登録する際にタグがテーブルに存在していなかったら、作成しcountに0を入れる。存在していなかったらfindしているだけ
      Tag.find_or_create_by(name: article_tag) do |tag|
        tag.count = 0
      end
    end
  end

  def self.tag_article(tag_name)
    where(['tag_name like?', "%#{sanitize_sql_like(tag_name)}%"])
  end

  def self.search(search_word)
    Article.where(['title LIKE ? OR tag_name LIKE ? OR body LIKE ?', "%#{sanitize_sql_like(search_word)}%",
                   "%#{sanitize_sql_like(search_word)}%", "%#{sanitize_sql_like(search_word)}%"])
  end

  def liked_by(target_user)
    likes.where(user_id: target_user).exists?
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :redirect_not_logged_in
  before_action :attribute_article, only: %i[edit article_confirm_edit update destroy]
  before_action :attribute_category_article, only: %i[ruby rails coldfusion sql others]
  before_action :attribute_tag, only: %i[home ruby rails coldfusion sql others]

  include(ArticlesHelper)

  def home
    @articles = Article.all.order(created_at: 'DESC')
    @switch_line = 'home'
  end

  def ruby
    @switch_line = 'ruby'
  end

  def rails
    @switch_line = 'rails'
  end

  def coldfusion
    @switch_line = 'coldfusion'
  end

  def sql
    @switch_line = 'sql'
  end

  def others
    @switch_line = 'others'
  end

  def index
    @tags = Tag.all
    @article = Article.find(1)
  end

  def show
    @article = Article.find(params[:id])
    @tag_lists = @article.tag_name.split(',')
  end

  def new
    @article = Article.new
    @categories = Category.all
    article_info_delete if params[:back].nil? # フォームの値のセッションを削除している
  end

  def article_confirm
    @article = Article.new(set_article_only_params.merge(set_category_only_params))
    @tag_lists = params[:article][:tag_name].split(',')
    article_info(@article) # フォームの値のセッションにいれている
    return if @article.valid?

    redirect_to new_article_path(back: 'true')
    flash[:error] = @article.errors.full_messages
  end

  def create
    @categories = Category.all
    @article = Article.new(set_article_params)
    tag_list = params[:article][:tag_name].split(',')
    if @article.save
      @article.save_tags(tag_list) # save_tagsというインスタンスメソッドを使って保存している。
      flash[:notice] = 'プロフィールの設定が完了しました'
      article_info_delete # フォームの値のセッションを削除している
      redirect_to article_path(@article)
    else
      redirect_to new_article_path(back: 'true')
      flash[:error] = @article.errors.full_messages
    end
  end

  def edit
    @categories = Category.all
    article_info_delete if params[:back].nil? # フォームの値のセッションを削除している
  end

  def article_confirm_edit
    @article.attributes = set_article_only_params2.merge(set_category_only_params)
    @tag_lists = params[:tag_name].split(',')
    article_info(@article) # フォームの値のセッションにいれている

    return if @article.valid?

    redirect_to edit_article_path(@article, back: 'true')
    flash[:error] = @article.errors.full_messages
  end

  def update
    @article.update(set_article_params)
    tag_list = params[:article][:tag_name].split(',')
    @article.save_tags(tag_list) # save_tagsというインスタンスメソッドを使って保存している。
    redirect_to article_path(@article)
    flash[:success] = '編集完了しました'
  end

  def destroy
    @article.destroy
    redirect_to root_path
    flash[:success] = '削除が完了しました'
  end

  private

  def set_article_only_params
    params.require(:article).permit(:title, :tag_name, :body, :user_id)
  end

  def set_category_only_params
    params.require(:category).permit(:category_id)
  end

  def set_article_only_params2
    params.permit(:title, :tag_name, :body, :user_id)
  end

  def set_article_params
    params.require(:article).permit(:title, :tag_name, :body, :user_id, :category_id)
  end

  def attribute_article
    @article = Article.find(params[:id])
  end

  def attribute_category_article
    category = Category.find_by(search_category: params[:action])
    @articles = Article.where(category_id: category).order(created_at: 'DESC')
  end

  def attribute_tag
    @search_tags = Tag.all.limit(9).order(count: 'DESC')
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
  def article_info(article)
    session[:article_title] = article.title
    session[:article_tag_name] = article.tag_name
    session[:category_id] = article.category_id
    session[:article_body] = article.body
  end

  def article_info_delete
    session.delete(:article_title)
    session.delete(:article_tag_name)
    session.delete(:article_body)
    session.delete(:category_id)
  end

  def template_guide
    "テンプレートを貼り
    一文字でも編集を加えたら右画面に表示されます"
  end
end

app/views/articles/_articles.html.erb
<%= form_with(url: search_path, method: :get, local: true, class: 'search_form') do |f| %>
  <%= f.text_field :word, class: 'search_form' %>
  <%= f.submit "検索", class: 'search_submit' %>
<% end %>

<div class="search_word">
  <p class="search_title">検索ワード</p>
  <div class="search_tags">
    <%= render 'search_tags', { search_tags: @search_tags }  %>
  </div>
</div>

<div class="article_main">
  <% if articles.present? %>
    <% articles.each do |article| %>
    <div class="article_part">
      <p class="article_top">
        <%= link_to "@#{article.user.name}", user_path(article.user_id), class: 'article_top_user_name' %>
        が
        <%= article.created_at.strftime('%Y年%m月%d日') %>
        に投稿
      </p>
      <div class="article_part_content">
        <%= link_to article.title, article_path(article), class: 'article_part_link' %> 
        <div class="tag_list">
          <% article.tag_name.split(',').each do |tag| %>
            <%= link_to tag_path(tag), class: 'tag_list_link' do %>
              <i class="fa fa-tags"></i>
              <p class="tag"><%= tag %></p>
            <% end %>
          <% end %>
        </div>
        <div class="article_category_likeBtn">
          <p class="article_category"><%= article.category.name %></p>
          <%# お気に入りボタンの配置 %>
          <div class="likes_part article_all" data-like-container data-is-liked=<%= article.liked_by(current_user.id) %>>
            <% # JSで表示非表示を制御するので、先にどちらも非表示で表示しておく %>
            <% if article.liked_by(current_user.id) %>
              <%= button_to like_path(article), class: 'like_btn', method: :delete, remote: true, data: { "cancel-like": true } do %>
                <i class="fas fa-heart heart"></i>
                <span class="like_count" data-count><%= article.likes.count %></span>
              <% end %>
            <% else %>
              <%= button_to article_likes_path(article), class: 'like_btn', method: :post, remote: true, data: { "like": true } do %>
                <i class="fas fa-heart" style="color: #a3a3a3;"></i>
                <span class="like_count" data-count><%= article.likes.count %></span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% else %>
    <div class="not_article">
      <i class="fa fa-frown-o "></i>
      <p class="not_article_msg">まだ投稿が一つもありません。</p>
    </div>
  <% end %>
</div>

app/views/articles/_search_tags.html.erb
<% search_tags.each do |search_tag| %>
  <%= link_to tag_path(search_tag.name), class: 'tag_list_link' do %>
    <i class="fa fa-tags"></i>
    <p class="tag"><%= search_tag.name %></p>
  <% end %>
<% end %>

app/views/articles/_template.html.erb
<div class="template">
  <div class="template_part">
    <button type="button" id="font_bold" class="template_btn" title="太文字" ontouchstart="">
      <i class="fa fa-bold "></i> 
    </button>
  </div>
  <div class="template_part">
    <button type="button" id="italics" class="template_btn" title="斜体" ontouchstart="">
      <i class="fa-solid fa-italic"></i>
    </button>
  </div>
  <div class="template_part">
    <button type="button" id="strikethrough" class="template_btn" title="打ち消し線" ontouchstart="">
      <i class="fa fa-strikethrough "></i> 
    </button>
  </div>
  <div class="template_part">
    <button type="button" id="heading" class="template_btn" title="見出し" ontouchstart="">
      <i class="fa-solid fa-h"></i>
    </button>
  </div>
  <div class="template_part">
    <button type="button" id="quote" class="template_btn" title="引用のテキスト挿入" ontouchstart="">
      <i class="fa-solid fa-quote-right"></i>
    </button>
  </div>
  <div class="template_part">
    <button type="button" id="code" class="template_btn" title="コードの挿入" ontouchstart="">
      <i class="fa-solid fa-code"></i>
    </button>
  </div>
  <div class="template_part">
    <button type="button" id="link" class="template_btn" title="リンクの挿入" ontouchstart="">
      <i class="fa fa-link "></i> 
    </button>
  </div>
  <div class="template_part">
    <button type="button" id="list" class="template_btn" title="リストの挿入" ontouchstart="">
      <i class="fa-solid fa-list"></i>
    </button>
  </div>
  <div class="template_part">
    <button type="button" id="number_list" class="template_btn" title="番号リストの挿入" ontouchstart="">
      <i class="fa-solid fa-list-ol"></i>
    </button>
  </div>
  <div class="template_part">
    <button type="button" id="dash" class="template_btn" title="水平線の挿入" ontouchstart="">
      <i class="fa-solid fa-minus" ></i>
    </button>
  </div>
  <div class="template_part2 template_icon">
    <button type="button" id="template" class="template_btn " title="<%= simple_format(template_guide) %>" ontouchstart="">
      <i class="fa fa-copy "></i> 
      テンプレ
    </button>
  </div>
</div>

app/views/articles/article_confirm.html.erb
<div class="article_confirm_title">投稿確認</div>
<%= form_with(model: @article, url: articles_path, local: true, class: 'article_form_confirm') do |f| %>
  <div class="title_confirm">
    <p class="confirm_title_p">タイトル</p>
    <h1 class="title_confirm_h1"><%= @article.title %></h1>
  </div>
  <div class="confirm_part">
    <div class="category_confirm">
      <p class="category_p confirm_title_p">カテゴリー</p>
      <p class="category_name"><%= @article.category.name %></p>
    </div>
    <div class="tag_confirm">
      <p class="tag_p confirm_title_p">タグ</p>
      <div class="tag_clump">
        <% @tag_lists.each do |tag| %>
          <div class="tag_part">
            <i class="fa fa-tags "></i>
            <p class="tag"><%= tag %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="center_line">
    <p class="content_markdown">内容</p>
  </div>
  <div class='article_markdown'>
    <%= markdown(@article.body) %>
  </div>
  <%= f.hidden_field :title, :value => @article.title %>
  <%= f.hidden_field :body, :value => @article.body %>
  <%= f.hidden_field :tag_name, :value => @article.tag_name %>
  <%= f.hidden_field :category_id, :value => @article.category_id %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= link_to '戻る', new_article_path(back: 'true'), class: "article_btn entry" %>
  <%= f.submit '登録', class: 'article_btn entry' %>
<% end %>

app/views/articles/article_confirm_edit.html.erb
<div class="edit_confirm_show">
  <div class="article_confirm_title">投稿確認</div>
  <%= form_with(model: @article, url: article_path(@article), local: true, class: 'article_form_confirm') do |f| %>
    <div class="title_confirm">
      <p class="confirm_title_p">タイトル</p>
      <h1 class="title_confirm_h1"><%= @article.title %></h1>
    </div>
    <div class="confirm_part">
      <div class="category_confirm">
        <p class="category_p confirm_title_p">カテゴリー</p>
        <p class="category_name"><%= @article.category.name %></p>
      </div>
      <div class="tag_confirm">
        <p class="tag_p confirm_title_p">タグ</p>
        <div class="tag_clump">
          <% @tag_lists.each do |tag| %>
            <div class="tag_part">
              <i class="fa fa-tags "></i>
              <p class="tag"><%= tag %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="center_line">
      <p class="content_markdown">内容</p>
    </div>
    <div class='article_markdown'>
      <%= markdown(@article.body) %>
    </div>
    
    <%= f.hidden_field :title, :value => @article.title %>
    <%= f.hidden_field :body, :value => @article.body %>
    <%= f.hidden_field :tag_name, :value => @article.tag_name %>
    <%= f.hidden_field :category_id, :value => @article.category_id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= link_to '戻る', edit_article_path(back: 'true'), class: "article_btn entry" %>
    <%= f.submit '登録', class: 'article_btn entry' %>
  <% end %>
</div>

app/views/articles/coldfusion.html.erb
<div class="home_title" style="display:flex;">
  <img class="article_home_icon coldfusion" src="/assets/coldfusion.png"/>
  <p class="home">ColdFusion</p>
</div>

<div class="application_title">
  <p>らくらくInfo</p>
  <h1>RakuRaku</h1>
</div>

<%= render 'articles', { articles: @articles }  %>

app/views/articles/edit.html.erb
<% if flash[:error].present? %>
  <div class="error_main">
    <p><%= flash[:error].count %>つのエラーが発生しました</p>
    <% flash[:error].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </div>
<% end %>
<p class="validates_error" id="validates_error">680文字を超えました。文字数を制限数以内にしてください。</p>
<p class="validates_tags_error" id="validates_tags_error">タグは5つまでです。</p>
<%= form_with(url: article_confirm_edit_article_path(@article), local: true) do |f| %>
  <div class='form-group'>
    <% if session[:article_title].present? %>
      <%= f.text_field :title, class: 'title_field', :placeholder => 'タイトル', :value => session[:article_title] %>
    <% else %>
      <%= f.text_field :title, class: 'title_field', :placeholder => 'タイトル', :value => @article.title %>
    <% end %>
  </div>
  <div class='form-group tag_category'>
    <%= fields_for :category do |category_f| %>
      <% if session[:category_id].present? %>
        <%= category_f.select :category_id, @categories.map{ |category| [category.name, category.id]}, selected: session[:category_id] %>
      <% else %>
        <%= category_f.select :category_id, @categories.map{ |category| [category.name, category.id]}, selected: @article.category_id %>
      <% end %>
    <% end %>
    <% if session[:article_tag_name].present? %>
      <%= f.text_field :tag_name, class: 'tag_field', :placeholder => 'タグを複数つけるには,(カンマ)で区切ってください(例：Ruby,Rails,SQL)', :value => session[:article_tag_name] %>
    <% else %>
      <%= f.text_field :tag_name, class: 'tag_field', :placeholder => 'タグを複数つけるには,(カンマ)で区切ってください(例：Ruby,Rails,SQL)', :value => @article.tag_name %>
    <% end %>
  </div>
  <div class='form-group'>
    <%= render 'template' %>
    <div id='editor'>
      <% if session[:article_body].present? %>
        <%= f.text_area :body, class: 'form-control text_area_markdown', id: 'note_explanation', "v-model" => "input", :placeholder => 'Markdown記法で書いて共有しよう', :value => session[:article_body], limit: "680" %>
      <% else %>
        <%= f.text_area :body, class: 'form-control text_area_markdown', id: 'note_explanation', "v-model" => "input", :placeholder => 'Markdown記法で書いて共有しよう', :value => @article.body, limit: "680" %>
      <% end %>
      <div v-html='input | marked' class="markdown_preview" id="template2"></div>
    </div>
  </div>
  <%= link_to '戻る', article_path(@article), class: "article_btn" %>
  <%= f.submit '登録', class: 'article_btn', id: 'article_btn' %>
  <div class="btn_validates">
    <span class="text_count">現在の文字数：<span id="moji_suu">0</span>字 (680文字以内)</span>
  </div>
<% end %>

<!-- リアルタイムプレビュー -->
<script type="text/javascript">
  window.onload = function() {
    new Vue({
    el: '#editor',
    data: {
      input: '<%= j @article.body %>',
    },
    filters: {
    marked: marked,
    },
    });
  };
</script>

app/views/articles/home.html.erb
<div class="home_title" style="display:flex;">
  <i class="fa fa-home article_home_icon"></i> 
  <p class="home">ホーム</p>
</div>

<div class="application_title">
  <p>らくらくInfo</p>
  <h1>RakuRaku</h1>
</div>

<%= render 'articles', { articles: @articles }  %>

app/views/articles/new.html.erb
<% if flash[:error].present? %>
  <div class="error_main">
    <p><%= flash[:error].count %>つのエラーが発生しました</p>
    <% flash[:error].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </div>
<% end %>
<p class="validates_error" id="validates_error">680文字を超えました。文字数を制限数以内にしてください。</p>
<p class="validates_tags_error" id="validates_tags_error">タグは5つまでです。</p>
<%= form_with(model: @article, url: article_confirm_new_article_path, local: true) do |f| %>
  <%= render 'shared/error', object: f.object %>
  <div class='form-group'>
    <%= f.text_field :title, class: 'title_field', :placeholder => 'タイトル', :value => session[:article_title] %>
  </div>
  <div class='form-group tag_category'>
    <%= fields_for :category do |category_f| %>
      <%= category_f.select :category_id, @categories.map{ |category| [category.name, category.id]}, selected: session[:category_id] %>
    <% end %>
    <%= f.text_field :tag_name, class: 'tag_field', :placeholder => 'タグを複数つけるには,(カンマ)で区切ってください(例：Ruby,Rails,SQL)', :value => session[:article_tag_name], id: 'tag_name' %>
  </div>
  <div class='form-group'>
    <%= render 'template' %>
    <div id='editor'>
      <%= f.text_area :body, class: 'text_area_markdown', id: 'note_explanation', "v-model" => "input", :placeholder => 'Markdown記法で書いて共有しよう', :value => session[:article_body], limit: "680" %>
    <div v-html='input | marked' class="markdown_preview" id="template2"></div>
    </div>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.submit '登録', class: 'article_btn', id: 'article_btn' %>
  <span class="markdown_show_preview" id="markdown_show_preview">プレビュー</span>
  <!--- 文字数表示場所 --->
  <div class="btn_validates">
    <span class="text_count">現在の文字数：<span id="moji_suu">0</span>字 (680文字以内)</span>
  </div>
<% end %>

<!-- リアルタイムプレビュー -->
<script type="text/javascript">
  window.onload = function() {
    new Vue({
    el: '#editor',
    data: {
      input: '<%= j @article.body %>',
    },
    filters: {
    marked: marked,
    },
    });
  };
</script>

app/views/articles/others.html.erb
<div class="home_title" style="display:flex;">
  <p class="home">その他</p>
</div>

<div class="application_title">
  <p>らくらくInfo</p>
  <h1>RakuRaku</h1>
</div>

<%= render 'articles', { articles: @articles }  %>

app/views/articles/rails.html.erb
<div class="home_title" style="display:flex;">
  <img class="rails" src="https://img.icons8.com/windows/128/000000/ruby-on-rails.png"/>
</div>

<div class="application_title">
  <p>らくらくInfo</p>
  <h1>RakuRaku</h1>
</div>

<%= render 'articles', { articles: @articles }  %>

app/views/articles/ruby.html.erb
<div class="home_title" style="display:flex;">
  <img class="article_home_icon ruby" src="https://img.icons8.com/ios-filled/150/000000/ruby-programming-language.png"/>
  <p class="home">Ruby</p>
</div>

<div class="application_title">
  <p>らくらくInfo</p>
  <h1>RakuRaku</h1>
</div>

<%= render 'articles', { articles: @articles }  %>

app/views/articles/show.html.erb
<div class="main">
  <div class="menu">
    <%# いいねボタンのハートボタン %>
    <div class="likes_part" data-like-container data-is-liked=<%= @article.liked_by(current_user.id) %>>
        <% # JSで表示非表示を制御するので、先にどちらも非表示で表示しておく %>
        <% if @article.liked_by(current_user.id) %>
          <%= button_to like_path(@article), class: 'like_btn', method: :delete, remote: true, data: { "cancel-like": true } do %>
            <i class="fas fa-heart heart"></i>
          <% end %>
        <% else %>
          <%= button_to article_likes_path(@article), class: 'like_btn', method: :post, remote: true, data: { "like": true } do %>
            <i class="fas fa-heart article_show_heart" ></i>
          <% end %>
        <% end %>
      </div>
    <%# 編集、削除ボタンのポチ● %>
    <% if current_user.id == @article.user_id %>
      <button class="article_menu_button" id="article_menu" onclick="clickBtn2();"> 
        <i class="fa-solid fa-ellipsis"></i>
      </button>
      <div class="edit_delete"  id="edit_button_delete">
        <div class="edit_btn">
          <i class="fa-solid fa-pencil"></i>
          <%= link_to '編集する', edit_article_path(@article) %>
        </div>
        <div class="delete_btn">
          <%= button_to article_path(@article), method: :delete, class: 'article_delete_btn', form: { data: { turbo_confirm: "削除しますか？" } } do %>
            <i class="fa-solid fa-trash-can"></i>
            <p class="delete">削除する</p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="article_show_main">
    <div class="article_user_date">
      <span style="font-weight:bold;">@</span><%= link_to "#{@article.user.name}", user_path(@article.user.id), class: 'user_name' %>
      <div class="create_update" style="display:flex;">
        <p class="article_date">投稿日 <%= @article.created_at.strftime('%Y年%m月%d日') %></p>
        <% if @article.created_at != @article.updated_at %>
          <p class="article_date">更新日 <%= @article.updated_at.strftime('%Y年%m月%d日') %></p>
        <% end %>
      </div>
    </div>
    <div class="title_tag">

      <h1 class="article_title"><%= @article.title %></h1>
      <div class="tag_clump_show">
          <% @tag_lists.each do |tag| %>
            <%= link_to tag_path(tag), class: 'tag_list_link' do %>
              <i class="fa fa-tags"></i>
              <p class="tag"><%= tag %></p>
            <% end %>
          <% end %>
        </div>
    </div>
    <div class='article_markdown'>
      <%= markdown(@article.body) %>
    </div>
  </div>
</div>
<div class="show_link_back">
  <%= link_to '戻る', root_path, class: "article_btn show" %>
</div>
<div class="footer_menu">
  <%# いいねボタンのハートボタン %>
    <div class="likes_part" data-like-container data-is-liked=<%= @article.liked_by(current_user.id) %>>
        <% # JSで表示非表示を制御するので、先にどちらも非表示で表示しておく %>
        <% if @article.liked_by(current_user.id) %>
          <%= button_to like_path(@article), class: 'like_btn', method: :delete, remote: true, data: { "cancel-like": true } do %>
            <i class="fas fa-heart heart"></i>
          <% end %>
        <% else %>
          <%= button_to article_likes_path(@article), class: 'like_btn', method: :post, remote: true, data: { "like": true } do %>
            <i class="fas fa-heart article_show_heart" ></i>
          <% end %>
        <% end %>
      </div>
    <%# 編集、削除ボタンのポチ● %>
    <%# 編集、削除ボタンのポチ● %>
    <% if current_user.id == @article.user_id %>
      <button class="article_menu_button" id="article_menu" onclick="clickBtn3();"> 
        <i class="fa-solid fa-ellipsis"></i>
      </button>
      <div class="edit_delete"  id="edit_delete2">
        <div class="edit_btn">
          <i class="fa-solid fa-pencil"></i>
          <%= link_to '編集する', edit_article_path(@article) %>
        </div>
        <div class="delete_btn">
          <%= button_to article_path(@article), method: :delete, class: 'article_delete_btn', form: { data: { turbo_confirm: "削除しますか？" } } do %>
            <i class="fa-solid fa-trash-can"></i>
            <p class="delete">削除する</p>
          <% end %>
        </div>
      </div>
    <% end %>
</div>
<script>
//初期表示は非表示
document.getElementById("edit_button_delete").style.visibility ="hidden";
document.getElementById("edit_delete2").style.visibility ="hidden";

function clickBtn2(){
	const edit_button_delete = document.getElementById("edit_button_delete");

	if(edit_button_delete.style.visibility=="visible"){
		// hiddenで非表示
		edit_button_delete.style.visibility ="hidden";
	}else{
		// visibleで表示
		edit_button_delete.style.visibility ="visible";
	}
}
function clickBtn3(){
	const edit_delete2 = document.getElementById("edit_delete2");

	if(edit_delete2.style.visibility=="visible"){
		// hiddenで非表示
		edit_delete2.style.visibility ="hidden";
	}else{
		// visibleで表示
		edit_delete2.style.visibility ="visible";
	}
}
</script>

app/views/articles/sql.html.erb
<div class="home_title" style="display:flex;">
  <img class="article_home_icon sql" src="https://img.icons8.com/metro/26/000000/sql.png"/>
  <p class="home">SQL</p>
</div>

<div class="application_title">
  <p>らくらくInfo</p>
  <h1>RakuRaku</h1>
</div>

<%= render 'articles', { articles: @articles }  %>