config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/search', to: 'searches#search'

  root 'articles#home'

  resources :users do
    post :user_confirm, on: :new
    resources :relationships, only: [:create]
    resource :relationships, only: [:destroy]
    get 'followings', to: 'relationships#followings', as: 'followings'
    get 'followers', to: 'relationships#followers', as: 'followers'
  end

  resources :likes, only: [:destroy]
  resources :articles do
    resources :likes, only: [:create]
    post :article_confirm, on: :new
    member do
      post :article_confirm_edit, action: :article_confirm_edit
    end

    collection do
      get 'home'
      get 'ruby'
      get 'rails'
      get 'coldfusion'
      get 'sql'
      get 'others'
    end
  end

  resources :tags, param: :name
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token

  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }, allow_nil: true

  has_many :artile, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :reverse_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # フォローした時の処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外す時の処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show articles likes edit update]
  def new
    @user = User.new
  end

  def user_confirm
    @user = User.new(users_params)
    render 'new' unless @user.valid?
  end

  def create
    @user = User.new(users_params)
    if @user.save
      login(@user)
      flash[:success] = '新規登録が出来ました'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @articles = Article.where(user_id: @user)
    if params[:like] == 'true'
      @liked_article_ids = Like.where(user_id: @user)
    else
      @articles = Article.where(user_id: @user)
    end
  end

  def articles
    if params[:like] == 'true' # プロフィール投稿一覧アクション
      @liked_article_ids = Like.where(user_id: @user)
    else
      @articles = Article.where(user_id: @user)
    end
  end

  def likes
    if params[:like] == 'true' # プロフィールいいね一覧アクション
      @liked_article_ids = Like.where(user_id: @user)
    else
      @articles = Article.where(user_id: @user)
    end
  end

  def edit; end

  def update
    if @user.update(users_params)
      flash[:success] = '編集が完了しました'
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy; end

  private

  def users_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # いいねボタンから投稿を一つずつ取得していくメソッド
  def likes_helper(liked_id)
    Article.find(liked_id.article_id)
  end

  # プロフィールの使用しているタグの表示メソッド
  def tag_lists(articles)
    hashes = []
    articles.each do |article_tag|
      hashes.push(article_tag.tag_name.split(',')) # 連想配列になるが使っているタグを全て取り出す
    end
    hashes.flatten.uniq # flattenで連想配列を一つの配列に変換し、uniqで重複を取り除いている
  end
end

app/views/users/_articles.html.erb
<ul class="nav_menu">
    <%= link_to '投稿', user_path(@user, like: 'false'), class: 'is_active' %>
    <%= link_to 'いいね', user_path(@user, like: 'true'), class: 'tab' %>
</ul>
<div class="nav_content">
    <div class="nav is_show">
    <% if articles.present? %>
        <% articles.each do |article| %>
            <div class="nav_article_part">
            <p class="article_top">
                @
                <%= link_to "#{article.user.name}", user_path(article.user_id), class: 'article_top_user_name' %>
                が
                <%= article.created_at.strftime('%Y年%m月%d日') %>
                に投稿
            </p>
            <%= link_to article.title, article_path(article), class: 'article_part_link' %> 
            <div class="tag_list">
                <i class="fa fa-tags"></i>
                <% article.tag_name.split(',').each do |tag| %>
                <%= link_to "#{tag}", tag_path(tag), class: 'tag_list_link' %>
                <% end %>
            </div>
            </div>
        <% end %>
    <% else %>
        <p class="not_like_article">投稿がありません。</p>
    <% end %>
    </div>
</div>

app/views/users/_likes.html.erb
<ul class="nav_menu">
    <%= link_to '投稿', user_path(@user, like: 'false'), class: 'tab' %>
    <%= link_to 'いいね', user_path(@user, like: 'true'), class: 'is_active' %>
</ul>
<div class="nav_content">
    <div class="nav is_show">
    <% if liked_article_ids.present? %>
        <% liked_article_ids.each do |likes_helper| %>
            <div class="nav_article_part">
            <p class="article_top">
                @
                <%= link_to "#{likes_helper.user.name}", user_path(likes_helper.user_id), class: 'article_top_user_name' %>
                が
                <%= likes_helper.created_at.strftime('%Y年%m月%d日') %>
                に投稿
            </p>
            <%= link_to likes_helper(likes_helper).title, article_path(likes_helper.article_id), class: 'article_part_link' %> 
            <div class="tag_list">
                <i class="fa fa-tags"></i>
                <% likes_helper(likes_helper).tag_name.split(',').each do |tag| %>
                <%= link_to "#{tag}", tag_path(tag), class: 'tag_list_link' %>
                <% end %>
            </div>
            </div>
        <% end %>
    <% else %>
        <p class="not_like_article">いいねした投稿がありません。</p>
    <% end %>
    </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1 class="login_header">RakuRaku</h1>
<div class="entry_top">
    <h2 class="step1" style="background: #55c500;color: white;">STEP1 入力</h2><div class="step1_triangle" style="border-left: 25px solid #55c500;"></div>
    <div class="a"></div>
    <h2 class="step2">STEP2 確認</h2><div class="step2_triangle"></div>
    <div class="a2"></div>
    <h2 class="step3">STEP3 完了</h2>
</div>

<p class="login_info_msg">ログインに使用する情報</p>
<%= form_with(model: @user, url: user_path(@user), local: true) do |f| %>
    <%= render 'shared/error', object: f.object %>
    <div class="entry_form">
    <p class="login_form_detail">氏名<span class="form_span">必須</sapn></p>
    <%= f.text_field :name, class: "form_input", :value => @user.name %>
    <p class="login_form_detail">メールアドレス (半角英数字)<span class="form_span">必須</sapn></p>
    <%= f.text_field :email, class: "form_input", :value => @user.email %>
    <p class="login_form_detail">パスワード(半角英数字)<span class="form_span">必須</sapn></p>
    <%= f.password_field :password, class: "form_input" %>
    <p class="login_form_detail">パスワード確認(半角英数字)<span class="form_span">必須</sapn></p>
    <%= f.password_field :password_confirmation, class: "form_input" %>
    <div class="entry_button_mass">
        <%= link_to '戻る', user_path(@user), class: "entry_button" %>
        <%= f.submit '確認' ,class: 'entry_button1' %>
    </div>
    </div>
<% end %>

app/views/users/new.html.erb
<h1 class="login_header">RakuRaku</h1>
<div class="entry_top">
  <h2 class="step1" style="background: #55c500;color: white;">STEP1 入力</h2><div class="step1_triangle" style="border-left: 25px solid #55c500;"></div>
  <div class="a"></div>
  <h2 class="step2">STEP2 確認</h2><div class="step2_triangle"></div>
  <div class="a2"></div>
  <h2 class="step3">STEP3 完了</h2>
</div>

<p class="login_info_msg">ログインに使用する情報</p>
<%= form_with(model: @user, url: user_confirm_new_user_path, local: true) do |f| %>
  <%= render 'shared/error', object: f.object %>
  <div class="entry_form">
    <p class="login_form_detail">氏名<span class="form_span">必須</sapn></p>
    <%= f.text_field :name, class: "form_input", :placeholder => "例)西野 倫也" %>
    <p class="login_form_detail">メールアドレス (半角英数字)<span class="form_span">必須</sapn></p>
    <%= f.text_field :email, class: "form_input", :placeholder => "例)project.mail@example.co.jp" %>
    <p class="login_form_detail">パスワード(半角英数字)<span class="form_span">必須</sapn></p>
    <%= f.password_field :password, class: "form_input" %>
    <p class="login_form_detail">パスワード確認(半角英数字)<span class="form_span">必須</sapn></p>
    <%= f.password_field :password_confirmation, class: "form_input" %>
    <div class="entry_button_mass">
      <%= link_to '戻る', login_path, class: "entry_button" %>
      <%= f.submit '確認' ,class: 'entry_button1' %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="profile_content">
  <%= render 'shared/profile_left', { articles: @articles, user: @user} %>

  <div class="profile_right">
    <% if params[:like] == 'true' %>
      <p class="profile_p_title">いいね一覧</p>
      <%= render 'likes', { liked_article_ids: @liked_article_ids } %>
    <% else %>
      <p class="profile_p_title">投稿一覧</p>
      <%= render 'articles', { articles: @articles } %>
    <% end %>
    
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/users/user_confirm.erb
<h1 class="login_header">RakuRaku</h1>
<div class="entry_top">
  <h2 class="step1">STEP1 入力</h2><div class="step1_triangle"></div>
  <div class="a" style="border-color: #55c500 transparent #55c500 transparent; "></div>
  <h2 class="step2"  style="background: #55c500;color: white;">STEP2 確認</h2><div class="step2_triangle" style="border-left: 25px solid #55c500;"></div>
  <div class="a2"></div>
  <h2 class="step3">STEP3 完了</h2>
</div>

<p class="login_info_msg">確認情報</p>
<%= form_with(model: @user, local: true) do |f| %>
  <div class="entry_form2">
    <p class="login_form_detail">氏名<span class="form_span">必須</sapn></p>
    <p class="entry_form_info"><%= @user.name %></p>
    <p class="login_form_detail">メールアドレス (半角英数字)<span class="form_span">必須</sapn></p>
    <p class="entry_form_info"><%= @user.email %></p>
    <p class="login_form_detail">パスワード(半角英数字)<span class="form_span">必須</sapn></p>
    <p class="entry_form_info"><%= @user.password %></p>
    <%= f.hidden_field :name  %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :password  %>
    <%= f.hidden_field :password_confirmation %>
    <div class="entry_button_mass">
      <%= link_to '戻る', :back, class: "entry_button" %>
      <%= f.submit '送信' ,class: 'entry_button1' %>
    </div>
  </div>
<% end %>

app/views/users/user_confirm_new.html.erb
<div class="entry_top">
  <h2 class="step1">STEP1 入力</h2><div class="step1_triangle"></div>
  <div class="a" style="border-color: #55c500 transparent #55c500 transparent; "></div>
  <h2 class="step2"  style="background: #55c500;color: white;">STEP2 確認</h2><div class="step2_triangle" style="border-left: 25px solid #55c500;"></div>
  <div class="a2"></div>
  <h2 class="step3">STEP3 完了</h2>
</div>

<p class="login_info_msg">確認情報</p>
<%= form_with(model: @user, local: true) do |f| %>
  <div class="entry_form2">
    <p class="login_form_detail">氏名<span class="form_span">必須</sapn></p>
    <p class="entry_form_info"><%= @user.name %></p>
    <p class="login_form_detail">メールアドレス (半角英数字)<span class="form_span">必須</sapn></p>
    <p class="entry_form_info"><%= @user.email %></p>
    <p class="login_form_detail">パスワード(半角英数字)<span class="form_span">必須</sapn></p>
    <p class="entry_form_info"><%= @user.password %></p>
    <%= f.hidden_field :name  %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :password  %>
    <%= f.hidden_field :password_confirmation %>
    <div class="entry_button_mass">
      <%= link_to '戻る', :back, class: "entry_button" %>
      <%= f.submit '送信' ,class: 'entry_button1' %>
    </div>
  </div>
<% end %>