config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/search', to: 'searches#search'

  root 'articles#home'

  resources :users do
    post :user_confirm, on: :new
    resources :relationships, only: [:create]
    resource :relationships, only: [:destroy]
    get 'followings', to: 'relationships#followings', as: 'followings'
    get 'followers', to: 'relationships#followers', as: 'followers'
  end

  resources :likes, only: [:destroy]
  resources :articles do
    resources :likes, only: [:create]
    post :article_confirm, on: :new
    member do
      post :article_confirm_edit, action: :article_confirm_edit
    end

    collection do
      get 'home'
      get 'ruby'
      get 'rails'
      get 'coldfusion'
      get 'sql'
      get 'others'
    end
  end

  resources :tags, param: :name
end

app/views/shared/_error.html.erb
<% if object.errors.any? %>
<div class="error_main">
  <p><%= object.errors.count %>つのエラーが発生しました</p>
  <% object.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
</div>
<% end %>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header_top">
    <%= link_to 'RukuRaku', root_path, class: 'header_left_link' %>
    
    <div class="header_right">
      <% if logged_in? %>
        <%= link_to 'プロフィール', user_path(current_user), class: 'profile' %>
        <%= link_to '記事投稿', new_article_path, class: 'article_btn' %>
        <%= button_to logout_path, method: :delete, class: 'logout_link' do %>
          <i class="fas fa-sign-out-alt"></i>
          <p class="sign_in_out">ログアウト</p>
        <% end %>
      <% else %>
        <%= link_to 'ログイン', logout_path, method: :delete, class: 'logout_link' %>
      <% end %>
    </div>
    <div id="nav-drawer">
        <input id="nav-input" type="checkbox" class="nav-unshown">
        <label id="nav-open" for="nav-input"><span></span></label>
        <label class="nav-unshown" id="nav-close" for="nav-input"></label>
        <div id="nav-content">
          <p class="header_slider_menu_title">
            RakuRaku
          </p>
          <ul>
            <li class="first_menu_li"><%= link_to 'ホーム', root_path, class: 'responsive_menu_link_part' %></li>
            <li><%= link_to 'プロフィール', user_path(current_user), class: 'responsive_menu_link_part' %></li>
            <li><%= link_to '記事投稿', new_article_path, class: 'responsive_menu_link_part' %></li>
            <li><%= button_to 'ログアウト', logout_path, method: :delete, class: 'responsive_menu_link_part last_menu' %></li>
          </ul>
        </div>
      </div>
  </div>
  
  <div class="header_bottom">
    <% if @switch_line == 'home' %>
      <%= link_to 'ホーム', home_articles_path, class: 'trend selecte' %>
    <% else %>
      <%= link_to 'ホーム', home_articles_path, class: 'trend' %>
    <% end %>
    <% if @switch_line == 'ruby' %>
      <%= link_to 'Ruby', ruby_articles_path, class: 'trend selecte' %>
    <% else %>
      <%= link_to 'Ruby', ruby_articles_path, class: 'trend' %>
    <% end %>
    <% if @switch_line == 'rails' %>
      <%= link_to 'Rails', rails_articles_path, class: 'trend selecte' %>
    <% else %>
      <%= link_to 'Rails', rails_articles_path, class: 'trend' %>
    <% end %>
    <% if @switch_line == 'coldfusion' %>
      <%= link_to 'ColdFusion', coldfusion_articles_path, class: 'trend c selecte' %>
    <% else %>
      <%= link_to 'ColdFusion', coldfusion_articles_path, class: 'trend c' %>
    <% end %>
    <% if @switch_line == 'sql' %>
      <%= link_to 'SQL', sql_articles_path, class: 'trend selecte' %>
    <% else %>
      <%= link_to 'SQL', sql_articles_path, class: 'trend' %>
    <% end %>
    <% if @switch_line == 'others' %>
      <%= link_to 'その他', others_articles_path, class: 'trend selecte' %>
    <% else %>
      <%= link_to 'その他', others_articles_path, class: 'trend' %>
    <% end %>
  </div>
</div>

app/views/shared/_like_button.html.erb
<div class="likes_part article_all" data-like-container data-is-liked=<%= article.liked_by(current_user.id) %>>
  <% # JSで表示非表示を制御するので、先にどちらも非表示で表示しておく %>
  <% if article.liked_by(current_user.id) %>
    <%= button_to like_path(article), class: 'like_btn', method: :delete, remote: true, data: { "cancel-like": true } do %>
      <i class="fas fa-heart heart"></i>
      <span class="like_count" data-count><%= article.likes.count %></span>
    <% end %>
  <% else %>
    <%= button_to article_likes_path(article), class: 'like_btn', method: :post, remote: true, data: { "like": true } do %>
      <i class="fas fa-heart" style="color: #a3a3a3;"></i>
      <span class="like_count" data-count><%= article.likes.count %></span>
    <% end %>
  <% end %>
</div>

app/views/shared/_profile_left.html.erb
<div class="profile_left">
    <div class="profile_left_top">
    <p class="myname">@<%= user.name %></p>
    <div class="profile_follow_list">

        <div class="my_article">
        <p class="count"><%= articles.count %></p>
        <p class="count_info">投稿</p>
        </div>

        <div class="my_follow">
        <p class="count"><%= user.followings.count %></p>
        <p class="count_info"><%= link_to 'フォロー', user_followings_path(user.id), class: 'followings_link_btn' %></p>
        </div>

        <div class="my_follower">
        <p class="count"><%= user.followers.count %></p>
        <p class="count_info"><%= link_to 'フォロワー', user_followers_path(user.id), class: 'followers_link_btn' %></p>
        </div>
    </div>

    <% if current_user.id != user.id %>
        <% if current_user.following?(user) %>
        <%= button_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: 'profile_edit' %>
        <% else %>
        <%= button_to 'フォローする', user_relationships_path(user.id), method: :post, class: 'profile_edit' %>
        <% end %>
    <% end %>

    <% if current_user.id == user.id %>
        <%= link_to 'プロフィールを編集する', edit_user_path(current_user.id), class: 'profile_edit' %>
    <% end %>

    </div>
    <div class="profile_left_bottom">
    <div class="use_tag_list_title">
        <i class="fa fa-tags"></i>
        <p>使用しているタグ</p>
    </div>
    <div class="use_tag_lists">
        <% tag_lists(articles).each do |tag| %>
            <%= link_to tag, tag_path(tag)  %>
        <% end %>
    </div>
    </div>
</div>