config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/search', to: 'searches#search'

  root 'articles#home'

  resources :users do
    post :user_confirm, on: :new
    resources :relationships, only: [:create]
    resource :relationships, only: [:destroy]
    get 'followings', to: 'relationships#followings', as: 'followings'
    get 'followers', to: 'relationships#followers', as: 'followers'
  end

  resources :likes, only: [:destroy]
  resources :articles do
    resources :likes, only: [:create]
    post :article_confirm, on: :new
    member do
      post :article_confirm_edit, action: :article_confirm_edit
    end

    collection do
      get 'home'
      get 'ruby'
      get 'rails'
      get 'coldfusion'
      get 'sql'
      get 'others'
    end
  end

  resources :tags, param: :name
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  def show
    @search_tags = Tag.all.limit(9).order(count: 'DESC') # tag8つまで取得している
    @tag = Tag.find_by(name: params[:name]) # タグのレコードを取得
    @articles = Article.tag_article(@tag.name) # タグ名で投稿名を検索している
    @tag.increment(:count, 1) # 表示順をタグをクリックされた回数分の降順にしている
    @tag.save
  end
end

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
end

app/views/tags/show.html.erb
<div class="application_title" style="margin-top: 20px;">
  <p>らくらくInfo</p>
  <h1>RakuRaku</h1>
</div>

<%= form_with(url: search_path, method: :get, local: true, class: 'search_form') do |f| %>
  <%= f.text_field :word, class: 'search_form' %>
  <%= f.submit "検索", class: 'search_submit' %>
<% end %>

<div class="search_word">
  <p class="search_title">検索ワード</p>
  <div class="search_tags">
    <% @search_tags.each do |search_tag| %>
      <%= link_to tag_path(search_tag.name), class: 'tag_list_link' do %>
        <i class="fa fa-tags"></i>
        <p class="tag"><%= search_tag.name %></p>
      <% end %>
    <% end %>
  </div>
</div>

<p class="tag_name_search_result"><i class="fa fa-tags"></i>「<%= @tag.name %>」の検索結果</p>

<div class="article_main">
  <% if @articles.present? %>
    <% @articles.each do |article| %>
    <div class="article_part">
      <p class="article_top">
        <%= link_to "@#{article.user.name}", user_path(article.user_id), class: 'article_top_user_name' %>
        が
        <%= article.created_at.strftime('%Y年%m月%d日') %>
        に投稿
      </p>
      <div class="article_part_content">
        <%= link_to article.title, article_path(article), class: 'article_part_link' %> 
        <div class="tag_list">
          <% article.tag_name.split(',').each do |tag| %>
            <%= link_to tag_path(tag), class: 'tag_list_link' do %>
              <i class="fa fa-tags"></i>
              <p class="tag"><%= tag %></p>
            <% end %>
          <% end %>    
        </div>
        <div class="article_category_likeBtn">
          <p class="article_category"><%= article.category.name %></p>
          <%= render 'shared/like_button', { article: article } %> <%# お気に入りボタンの配置 %>
        </div>
      </div>
    </div>
  <% end %>
  <% else %>
    <div class="not_article">
      <i class="fa fa-frown-o "></i> 
      <p class="not_article_msg">まだ投稿が一つもありません。</p>
    </div>
  <% end %>
</div>